import Head from "next/head";
import {
  Container,
  Heading,
  Table,
  Tbody,
  Td,
  Th,
  Thead,
  Tr,
} from "@chakra-ui/react";
import { useEffect, useState } from "react";
import { axiosInstance } from "../lib/axios";

// chakra ui --> CSS Framework✅
// formik --> Handle forms
// yup --> validate
// axios --> API Calls✅
// react-query --> manage API Calls(caching, state ,dll )

export default function Home() {
  const [products, setPordructs] = useState([]); //menyimpan data response GET

  // mau ngambil data api, harus bikin func dulu !
  const fectProducts = async () => {
    // handle erro menggunakan trycatch
    try {
      const productsResponse = await axiosInstance.get("/products");
      setPordructs(productsResponse.data);
    } catch (error) {
      console.log(error);
    }
  };
  // tamplate pengambilan data dari api ke table row
  // Hari ini baru sampai sini😏👌 mau lanjut odin project dulu
  // tahap setup , npm run dev ract,nodemon(nodejs),npc prisma client, and itu aja sihhh Cemanagatt uwekkk
  const renderProducts = () => {
    return products.map((product) => {
      return (
        <Tr key={product.id.toString()}>
          <Td>{product.id}</Td>
          <Td>{product.name}</Td>
          <Td>{product.price}</Td>
          <Td>{product.description}</Td>
          <Td>{product.image}</Td>
        </Tr>
      );
    });
  };

  // otamatis manggil fucn fectProduct menggunakan Hook useEffect
  useEffect(() => {
    fectProducts();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Heading>Hello World</Heading>
          <Table>
            <Thead>
              <Tr>
                <Th>Id</Th>
                <Th>Name</Th>
                <Th>Price</Th>
                <Th>Description</Th>
                <Th>Image</Th>
              </Tr>
            </Thead>
            <Tbody>{renderProducts()}</Tbody>
          </Table>
        </Container>
      </main>
    </>
  );
}
